.TH "gdalsrsinfo" 1 "Mon Aug 26 2013" "GDAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdalsrsinfo \- .TH "gdalsrsinfo" 1 "Mon Aug 26 2013" "GDAL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdalsrsinfo \- lists info about a given SRS in number of formats (WKT, PROJ.4, etc.)
.SH "SYNOPSIS"
.PP
.PP
.nf

Usage: gdalsrsinfo [options] srs_def

srs_def may be the filename of a dataset supported by GDAL/OGR from which to extract SRS information
OR any of the usual GDAL/OGR forms (complete WKT, PROJ.4, EPSG:n or a file containing the SRS)

Options: 
   [--help-general] [-h]  Show help and exit
   [-p]                   Pretty-print where applicable (e.g. WKT)
   [-V]                   Validate SRS
   [-o out_type]          Output type { default, all, wkt_all, proj4,
                                        wkt, wkt_simple, wkt_noct, wkt_esri,
                                        mapinfo, xml }

.fi
.PP
.SH "DESCRIPTION"
.PP
The gdalsrsinfo utility reports information about a given SRS from one of the following:
.PP
.IP "\(bu" 2
The filename of a dataset supported by GDAL/OGR which contains SRS information
.IP "\(bu" 2
Any of the usual GDAL/OGR forms (complete WKT, PROJ.4, EPSG:n or a file containing the SRS)
.PP
.PP
Output types:
.PP
.IP "\(bu" 2
\fBdefault\fP   proj4 and wkt (default option)
.IP "\(bu" 2
\fBall\fP   all options available
.IP "\(bu" 2
\fBwkt_all\fP   all wkt options available
.IP "\(bu" 2
\fBproj4\fP   PROJ.4 string
.IP "\(bu" 2
\fBwkt\fP   OGC WKT format (full)
.IP "\(bu" 2
\fBwkt_simple\fP   OGC WKT (simplified)
.IP "\(bu" 2
\fBwkt_noct\fP   OGC WKT (without OGC CT params)
.IP "\(bu" 2
\fBwkt_esri\fP   ESRI WKT format
.IP "\(bu" 2
\fBmapinfo\fP   Mapinfo style CoordSys format
.IP "\(bu" 2
\fBxml\fP   XML format (GML based)
.PP
.PP

.br
 
.SH "EXAMPLE"
.PP
.PP
.nf

$  gdalsrsinfo   "EPSG:4326"

PROJ.4 : '+proj=longlat +datum=WGS84 +no_defs '

OGC WKT :
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]

.fi
.PP
.PP

.br
 
.PP
.nf

$ gdalsrsinfo -o proj4 osr/data/lcc_esri.prj
'+proj=lcc +lat_1=34.33333333333334 +lat_2=36.16666666666666 +lat_0=33.75 +lon_0=-79 +x_0=609601.22 +y_0=0 +datum=NAD83 +units=m +no_defs '

.fi
.PP
.PP

.br
 
.PP
.nf

$ gdalsrsinfo -o proj4 landsat.tif
PROJ.4 : '+proj=utm +zone=19 +south +datum=WGS84 +units=m +no_defs '

.fi
.PP
.PP

.br
 
.PP
.nf

$ gdalsrsinfo  -o wkt -p  "EPSG:32722"

PROJCS["WGS 84 / UTM zone 22S",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",-51],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",10000000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","32722"]]

.fi
.PP
.PP

.br
 
.PP
.nf

$ gdalsrsinfo  -o wkt_all  "EPSG:4618"

OGC WKT :
GEOGCS["SAD69",
    DATUM["South_American_Datum_1969",
        SPHEROID["GRS 1967 Modified",6378160,298.25,
            AUTHORITY["EPSG","7050"]],
        TOWGS84[-57,1,-41,0,0,0,0],
        AUTHORITY["EPSG","6618"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4618"]]

OGC WKT (simple) :
GEOGCS["SAD69",
    DATUM["South_American_Datum_1969",
        SPHEROID["GRS 1967 Modified",6378160,298.25],
        TOWGS84[-57,1,-41,0,0,0,0]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433]]

OGC WKT (no CT) :
GEOGCS["SAD69",
    DATUM["South_American_Datum_1969",
        SPHEROID["GRS 1967 Modified",6378160,298.25]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433]]

ESRI WKT :
GEOGCS["SAD69",
    DATUM["D_South_American_1969",
        SPHEROID["GRS_1967_Truncated",6378160,298.25]],
    PRIMEM["Greenwich",0],
    UNIT["Degree",0.017453292519943295]]

.fi
.PP
.SH "AUTHORS"
.PP
Frank Warmerdam <warmerdam@pobox.com>, Etienne Tourigny <etourigny.dev-at-gmail-dot-com> 
